import Hero from "../components/layout/Hero";
import ServiceCard from "../components/site/ServiceCard";
import CaseStudyCard from "../components/site/CaseStudyCard";
import FAQ from "../components/site/FAQ";
import FinalCTA from "../components/site/FinalCTA";
import Icon from "../components/ui/Icon";
import { caseStudies, integrations, services } from "../data/siteData";

const values = [["spark", "AI-Powered Workflows"], ["code", "Custom Software Systems"], ["link", "API Integrations"], ["growth", "Growth Automation"]] as const;
const process = [["01", "Discover", "We map your process, bottlenecks, tools, and business goals."], ["02", "Design", "We shape the architecture, workflows, automations, and user experience."], ["03", "Build", "We integrate, test, and optimize using the right AI and software stack."], ["04", "Scale", "We improve and expand the system as your business grows."]];
const benefits = ["Systems designed around real business operations", "AI and automation built for measurable outcomes", "Clear documentation and handover", "Scalable infrastructure, not temporary fixes", "Modern UX for teams and customers", "Ongoing optimization and support"];

export default function Home() {
  return <><Hero />
    <section className="value-strip"><div className="container"><p>Built for teams that want to automate, scale, and move faster.</p><div>{values.map(([icon, label]) => <span key={label}><Icon name={icon}/>{label}</span>)}</div></div></section>
    <section className="section" id="services"><div className="container"><header className="section-heading"><div><span className="eyebrow">CAPABILITIES</span><h2>What We Build</h2></div><p>From AI agents to full business systems, we build technology that removes bottlenecks and creates leverage.</p></header><div className="service-grid">{services.map(service => <ServiceCard key={service.title} service={service}/>)}</div></div></section>
    <section className="section process-section" id="systems"><div className="container"><header className="section-heading centered"><span className="eyebrow">OUR PROCESS</span><h2>From Idea to Intelligent System</h2><p>A clear, practical path from operational friction to reliable infrastructure.</p></header><div className="process-line">{process.map(([number, title, copy]) => <article key={title}><span>{number}</span><div className="process-dot"/><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
    <section className="section"><div className="container"><header className="section-heading"><div><span className="eyebrow">FEATURED SYSTEMS</span><h2>Systems Built to Create Real Leverage</h2></div><p>Examples of connected systems that turn fragmented work into a reliable operating advantage.</p></header><div className="case-grid">{caseStudies.map(item => <CaseStudyCard key={item.title} item={item}/>)}</div></div></section>
    <section className="section"><div className="container why-grid"><div className="why-copy"><span className="eyebrow">WHY TECHQUARTERS AI</span><h2>Built for Businesses That Want More Than Basic Automation</h2><p>We don’t just connect tools. We design systems that make work faster, clearer, and easier to scale.</p><div className="signal-card"><i/><span>System health</span><b>All workflows operational</b><small>Live monitoring · Error handling · Human control</small></div></div><div className="benefits glass-card">{benefits.map(benefit => <div key={benefit}><span><Icon name="check"/></span><p>{benefit}</p></div>)}</div></div></section>
    <section className="section integration-section"><div className="container"><header className="section-heading centered"><span className="eyebrow">CONNECTED BY DESIGN</span><h2>Works With the Tools Your Business Already Uses</h2><p>One reliable system across the platforms your team depends on.</p></header><div className="integration-grid">{integrations.map((name, index) => <div key={name}><span>{name.slice(0, 2)}</span>{name}<small>0{(index % 4) + 1}</small></div>)}</div></div></section>
    <section className="section testimonials"><div className="container"><header className="section-heading centered"><span className="eyebrow">CLIENT IMPACT</span><h2>Built to Make Teams Faster</h2></header><div className="testimonial-grid"><blockquote><p>“TechQuarters AI helped us turn a manual, time-consuming process into a system that runs quietly in the background every day.”</p><footer><span>AM</span><div><b>Alex Morgan</b><small>Operations Director · Northstar</small></div></footer></blockquote><blockquote><p>“The team understood the business problem first, then built the technology. That made all the difference.”</p><footer><span>JR</span><div><b>Jamie Rivera</b><small>Founder · Form & Field</small></div></footer></blockquote><blockquote><p>“We finally have one clear view of our pipeline and the automation to keep every opportunity moving.”</p><footer><span>SL</span><div><b>Sam Lee</b><small>Head of Growth · Atlas Works</small></div></footer></blockquote></div><p className="placeholder-note">Representative placeholder testimonials — ready for approved client proof.</p></div></section>
    <section className="section"><div className="container faq-grid"><div><span className="eyebrow">COMMON QUESTIONS</span><h2>Clear Answers Before We Start</h2><p>Still wondering where to begin? Start a chat and describe the process that’s slowing you down.</p></div><FAQ /></div></section>
    <FinalCTA />
  </>;
}
